Repository ZhongAnTech/zarm, pull requests merged in 2022-12, with the labels that each got.

#992 refactor: css var
  package.json
  packages/zarm/src/collapse/index.ts
  packages/zarm/src/config-provider/cssVars.ts
  packages/zarm/src/config-provider/setTheme.ts
  packages/zarm/src/date-select/style/component.scss
  packages/zarm/src/index.ts
  packages/zarm/src/list/demo.md
  packages/zarm/src/list/style/component.scss
  packages/zarm/src/loading/Loading.tsx
  packages/zarm/src/loading/index.ts
  packages/zarm/src/loading/style/component.scss
  packages/zarm/src/nav-bar/index.ts
  packages/zarm/src/panel/index.tsx
  packages/zarm/src/popup/style/component.scss
  packages/zarm/src/radio/index.ts
  packages/zarm/src/search-bar/index.ts
  packages/zarm/src/style/themes/default.scss
  packages/zarm/src/tab-bar/index.ts
  packages/zarm/src/tabs/index.ts
Labels: PR: reviewed-approved

#993 docs: migration to v3
  packages/site/locale/en-US.js
  packages/site/locale/zh-CN.js
  packages/site/site.config.js
  packages/site/web/docs/migration-v3.md
Labels: PR: unreviewed

#994 fix: affix like #905
  packages/zarm/src/affix/__tests__/__snapshots__/index.test.tsx.snap
  packages/zarm/src/affix/index.tsx
Labels: PR: unreviewed

#995 docs: add diff example
  packages/site/web/docs/migration-v3.md
  packages/site/zarm.config.js
Labels: PR: unreviewed

#997 fix: code lint error
  packages/site/web/index.js
Labels: PR: unreviewed

#1001 refactor: improve pinchZoom test coverage
  packages/zarm/src/pinch-zoom/__tests__/index.test.tsx
Labels: PR: unreviewed

#1000 fix: v3 check
  packages/site/web/docs/migration-v3.md
  packages/zarm/src/action-sheet/ActionSheet.tsx
  packages/zarm/src/action-sheet/demo.md
  packages/zarm/src/action-sheet/style/component.scss
  packages/zarm/src/calendar/Calendar.tsx
  packages/zarm/src/calendar/demo.md
  packages/zarm/src/calendar/style/component.scss
  packages/zarm/src/cascader-view/CascaderView.tsx
  packages/zarm/src/cascader-view/demo.md
  packages/zarm/src/cascader-view/style/component.scss
  packages/zarm/src/cascader/Cascader.tsx
  packages/zarm/src/checkbox/CheckboxGroup.tsx
  packages/zarm/src/custom-input/CustomInput.tsx
  packages/zarm/src/file-picker/demo.md
  packages/zarm/src/file-picker/index.tsx
  packages/zarm/src/file-picker/style/component.scss
  packages/zarm/src/index.ts
  packages/zarm/src/input/Input.tsx
  packages/zarm/src/keyboard/demo.md
  packages/zarm/src/keyboard/style/component.scss
  packages/zarm/src/message/style/component.scss
  packages/zarm/src/modal/Modal.tsx
  packages/zarm/src/modal/demo.md
  packages/zarm/src/modal/style/component.scss
  packages/zarm/src/popper/demo.md
  packages/zarm/src/popper/index.tsx
  packages/zarm/src/popup/style/component.scss
  packages/zarm/src/progress/demo.md
  packages/zarm/src/progress/style/mixins.scss
  packages/zarm/src/pull/Pull.tsx
  packages/zarm/src/radio/Radio.tsx
  packages/zarm/src/radio/RadioGroup.tsx
  packages/zarm/src/rate/style/index.scss
  packages/zarm/src/scroller/__tests__/index.test.tsx
  packages/zarm/src/scroller/demo.md
  packages/zarm/src/scroller/index.tsx
  packages/zarm/src/scroller/style/index.tsx
  packages/zarm/src/search-bar/SearchBar.tsx
  packages/zarm/src/slider/demo.md
  packages/zarm/src/slider/index.tsx
  packages/zarm/src/slider/style/component.scss
  packages/zarm/src/stepper/Stepper.tsx
  packages/zarm/src/stepper/demo.md
  packages/zarm/src/stepper/style/component.scss
  packages/zarm/src/switch/index.tsx
Labels: PR: draft

#1006 chore: fix spelling mistakes
  packages/zarm/src/tabs/Tabs.tsx
Labels: PR: unreviewed

#1005 test: improve test coverage
  packages/zarm/src/__tests__/index.test.ts
  packages/zarm/src/back-top/__tests__/index.test.tsx
  packages/zarm/src/calendar/__tests__/index.test.tsx
Labels: PR: unreviewed

#996 refactor: @use-gesture 替换useDrag
  packages/zarm/src/__tests__/index.test.ts
  packages/zarm/src/carousel/__tests__/index.test.tsx
  packages/zarm/src/carousel/demo.md
  packages/zarm/src/carousel/index.tsx
  packages/zarm/src/carousel/interface.ts
  packages/zarm/src/carousel/style/component.scss
  packages/zarm/src/tabs/Tabs.tsx
Labels: PR: unreviewed
